[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -m compileall trm_api/",
    "python -c 'import trm_api.main; print(\"✅ TRM-OS API imported successfully\")'"
]

[start]
cmd = "uvicorn trm_api.main:app --host 0.0.0.0 --port $PORT --workers 4"

[variables]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info" 