import pytest
from unittest.mock import MagicMock, patch
from datetime import datetime

from trm_api.services.relationship_service import RelationshipService
from trm_api.models.relationships import Relationship, TargetEntityTypeEnum


class TestGeneratesKnowledgeRelationship:
    """Test cases for GENERATES_KNOWLEDGE relationship between Win and KnowledgeSnippet."""
    
    def setup_method(self):
        """Setup test fixtures."""
        self.service = RelationshipService()
        self.win_id = "win-123"
        self.knowledge_snippet_id = "snippet-456"
        
        # Sample relationship data
        self.win_knowledge_relationship = {
            "source_id": self.win_id,
            "source_type": "Win",
            "target_id": self.knowledge_snippet_id,
            "target_type": "KnowledgeSnippet",
            "type": "GENERATES_KNOWLEDGE",
            "createdAt": datetime.now(),
            "relationshipId": "rel-789",
            "notes": "Win generated valuable knowledge snippet"
        }
    
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    def test_create_generates_knowledge_relationship(self, mock_get_db):
        """Test creating a GENERATES_KNOWLEDGE relationship from Win to KnowledgeSnippet."""
        # Mock setup
        mock_session = MagicMock()
        mock_tx = MagicMock()
        mock_result = MagicMock()
        mock_record = MagicMock()
        
        mock_record.__getitem__.side_effect = lambda key: self.win_knowledge_relationship.get(key)
        mock_result.single.return_value = mock_record
        mock_tx.run.return_value = mock_result
        
        # Chuẩn bị mock cho sync
        relationship_obj = Relationship(**self.win_knowledge_relationship)
        
        # Thiết lập mock đúng cách cho sync
        mock_session.execute_write.return_value = relationship_obj
        
        mock_session_context = MagicMock()
        mock_session_context.__enter__.return_value = mock_session
        mock_session_context.__exit__.return_value = None
        
        # Quan trọng: Cấu hình _get_db để có thể sử dụng với sync
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_context
        mock_get_db.return_value = mock_db
        
        # Create relationship properties
        rel_props = {
            "relationshipId": self.win_knowledge_relationship["relationshipId"],
            "notes": self.win_knowledge_relationship["notes"]
        }
        
        # Execute test without await
        result = self.service.create_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.knowledge_snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE",
            relationship_properties=rel_props
        )
        
        # Assertions
        assert result is not None
        
        # Kiểm tra kết quả có thể là đối tượng Relationship hoặc dictionary
        if isinstance(result, dict):
            assert result["source_id"] == self.win_id
            assert result["source_type"] == "Win"
            assert result["target_id"] == self.knowledge_snippet_id
            assert result["target_type"] == "KnowledgeSnippet"
            assert result["type"] == "GENERATES_KNOWLEDGE"
        else:
            assert result.source_id == self.win_id
            assert result.source_type == "Win"
            assert result.target_id == self.knowledge_snippet_id
            assert result.target_type == "KnowledgeSnippet"
            assert result.type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
    
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    def test_get_knowledge_snippets_by_win(self, mock_get_db):
        """Test getting KnowledgeSnippets generated by a Win."""
        # Mock setup
        mock_session = MagicMock()
        mock_relationships = [Relationship(**self.win_knowledge_relationship)]
        
        # Thiết lập mock đúng cách cho sync
        mock_session.execute_read.return_value = mock_relationships
        
        mock_session_context = MagicMock()
        mock_session_context.__enter__.return_value = mock_session
        mock_session_context.__exit__.return_value = None
        
        # Quan trọng: Cấu hình _get_db để có thể sử dụng với sync
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_context
        mock_get_db.return_value = mock_db
        
        # Execute test without await
        results = self.service.get_relationships(
            entity_id=self.win_id,
            entity_type=TargetEntityTypeEnum.WIN,
            direction="outgoing",
            relationship_type="GENERATES_KNOWLEDGE",
            related_entity_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET
        )
        
        # Assertions
        assert len(results) == 1
        assert results[0].source_id == self.win_id
        assert results[0].target_id == self.knowledge_snippet_id
        assert results[0].type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.execute_read.assert_called_once()
    
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    def test_get_wins_by_knowledge_snippet(self, mock_get_db):
        """Test getting Wins that generated a KnowledgeSnippet."""
        # Mock setup
        mock_session = MagicMock()
        mock_relationships = [Relationship(**self.win_knowledge_relationship)]
        
        # Thiết lập mock đúng cách cho sync
        mock_session.execute_read.return_value = mock_relationships
        
        mock_session_context = MagicMock()
        mock_session_context.__enter__.return_value = mock_session
        mock_session_context.__exit__.return_value = None
        
        # Quan trọng: Cấu hình _get_db để có thể sử dụng với sync
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_context
        mock_get_db.return_value = mock_db
        
        # Execute test without await
        results = self.service.get_relationships(
            entity_id=self.knowledge_snippet_id,
            entity_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            direction="incoming",
            relationship_type="GENERATES_KNOWLEDGE",
            related_entity_type=TargetEntityTypeEnum.WIN
        )
        
        # Assertions
        assert len(results) == 1
        assert results[0].source_id == self.win_id
        assert results[0].target_id == self.knowledge_snippet_id
        assert results[0].type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.execute_read.assert_called_once()
    
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    def test_delete_generates_knowledge_relationship(self, mock_get_db):
        """Test deleting a GENERATES_KNOWLEDGE relationship."""
        # Mock setup
        mock_session = MagicMock()
        mock_summary = MagicMock()
        mock_summary.counters.relationships_deleted = 1
        
        mock_result = MagicMock()
        mock_result.consume.return_value = mock_summary
        
        mock_tx = MagicMock()
        mock_tx.run.return_value = mock_result
        
        # Thiết lập mock đúng cách cho sync
        mock_session.execute_write.return_value = True
        
        mock_session_context = MagicMock()
        mock_session_context.__enter__.return_value = mock_session
        mock_session_context.__exit__.return_value = None
        
        # Quan trọng: Cấu hình _get_db để có thể sử dụng với sync
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_context
        mock_get_db.return_value = mock_db
        
        # Execute test without await
        result = self.service.delete_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.knowledge_snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE"
        )
        
        # Assertions
        assert result is True
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
    
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    def test_delete_generates_knowledge_relationship_not_found(self, mock_get_db):
        """Test deleting a non-existent GENERATES_KNOWLEDGE relationship."""
        # Mock setup
        mock_session = MagicMock()
        mock_summary = MagicMock()
        mock_summary.counters.relationships_deleted = 0
        
        mock_result = MagicMock()
        mock_result.consume.return_value = mock_summary
        
        mock_tx = MagicMock()
        mock_tx.run.return_value = mock_result
        
        # Thiết lập mock đúng cách cho sync
        mock_session.execute_write.return_value = False
        
        mock_session_context = MagicMock()
        mock_session_context.__enter__.return_value = mock_session
        mock_session_context.__exit__.return_value = None
        
        # Quan trọng: Cấu hình _get_db để có thể sử dụng với sync
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_context
        mock_get_db.return_value = mock_db
        
        # Execute test without await
        result = self.service.delete_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.knowledge_snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE"
        )
        
        # Assertions
        assert result is False
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
